-
  name: Create EC2 instance with termination protection turned on
  hosts: localhost
  connection: local # Tells ansible it runs on same device
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "my-ec2-instance"
        key_name: "general-key-pair" # key present in aws
        # vpc_subnet_id: "subnet-5ca1ab1e"
        instance_type: "t2.micro"
        security_group: default
        region: "ap-south-1"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}" # From vault as defined
        image_id: "ami-0e35ddab05955cf57"
        network:
          assign_public_ip: true